server:
  port: 8082
spring:
  application:
    name: biz-cases-web
eureka:
  client:
    service-url:
      defaultZone: http://erueka-master.superbio.cn:8100/eureka/,http://erueka-slave.superbio.cn:8101/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
swagger:
  enabled: true
  base-package: cn.superbio.judicial.realization.controller
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 40000
  ConnectTimeout: 4000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000